### ISSUE TITLE
Model's specific naming  causes Type Error

### ISSUE THREAD

**Issue by tania-pets** [lykmapipo/sails-hook-seed#1]
sails  v0.11.1, sails-hook-seed v0.2.1.
A super simple model with name "Stage" and a "StageSeed.js" in the seeds dir does not work.
When i just rename the model-seed files, it works perfectly fine just like the rest models.
Is it a reserved word or something?

models/Stage.js
`module.exports = {
  attributes: {
    name : { type: 'string', maxLength: 100, notNull:true }
  }
};
`
seeds/development/StageSeed.js
`module.exports = [
    {name: "Κοιμούμενος οφθαλμός" }];
`
Error:
`
TypeError: Cannot call method 'findOrCreate' of undefined
    at /var/projects/3dapi/node_modules/sails-hook-seed/lib/work.js:66:23
    at /var/projects/3dapi/node_modules/sails/node_modules/async/lib/async.js:570:21
    at /var/projects/3dapi/node_modules/sails/node_modules/async/lib/async.js:249:17
    at /var/projects/3dapi/node_modules/sails/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/var/projects/3dapi/node_modules/sails/node_modules/async/lib/async.js:46:24)
    at async.each (/var/projects/3dapi/node_modules/sails/node_modules/async/lib/async.js:124:9)
    at _asyncMap (/var/projects/3dapi/node_modules/sails/node_modules/async/lib/async.js:248:13)
    at Object.map (/var/projects/3dapi/node_modules/sails/node_modules/async/lib/async.js:219:23)
    at _parallel (/var/projects/3dapi/node_modules/sails/node_modules/async/lib/async.js:568:20)
    at Object.async.parallel (/var/projects/3dapi/node_modules/sails/node_modules/async/lib/async.js:598:9)
    at module.exports (/var/projects/3dapi/node_modules/sails-hook-seed/lib/load.js:34:14)
    at /var/projects/3dapi/node_modules/sails-hook-seed/index.js:48:21
    at /var/projects/3dapi/node_modules/sails/lib/app/private/after.js:91:14
    at /var/projects/3dapi/node_modules/sails/node_modules/async/lib/async.js:254:17
    at done (/var/projects/3dapi/node_modules/sails/node_modules/async/lib/async.js:135:19)
`

**Comment by lykmapipo** [comment]
@tania-pets
- Under which environment you run your sails application? 
- After rename `StageSeed.js` seed data file, what is the name of the file you used then?

Am on it

**Comment by tania-pets** [comment]
I am on Ubuntu 14.04 (trusty).
I tried multiple different names (of course changed both model and seed file), all of them worked fine.
I kept Phase.js for model and PhaseSeed.js for seed file.
Issue occured  ONLY with "Stage".

**Comment by lykmapipo** [comment]
@tania-pets 

Ok..Let verify the issue with `StageSeed.js`

**Comment by pschuegr** [comment]
Pretty sure this is a result of how the model name is being obtained:

https://github.com/lykmapipo/sails-hook-seed/blob/master/lib/work.js#L17

Probably better off just to do something like this:

```
var modelGlobalId = seed.replace(/Seed$/, '').toLowerCase();
```

**Comment by lykmapipo** [comment]
@pschuegr & @tania-pets 

I have merge a pull request from @pschuegr which fix the issue.

Thanks @pschuegr for the patches

**Comment by lykmapipo** [comment]
@tania-pets 

I have publish [v0.2.2](https://github.com/lykmapipo/sails-hook-seed/tree/v0.2.2) into npm which fix the issue.

Thanks.
