### ISSUE TITLE
Logging on startup

### ISSUE THREAD

**Issue by kodayashi** [lykmapipo/sails-hook-seed#4]
Nice module, good stuff.

It'd be great if some logging was in place to show users what's going on when sails starts up and the seeding logic fires, especially if there are any errors seeding the db. Perhaps even capturing output from the DB itself and showing it would be cool (e.g. rails seeding).

**Comment by lykmapipo** [comment]
@kodayashi 

May you please share an image show how rails seeding logs its outputs.
Think its a nice feature to implement

**Comment by lykmapipo** [comment]
+1

**Comment by kodayashi** [comment]
Gah, my bad. The output I was thinking of in rails is generated during db migrations, not the seed process. Rails users are in charge of their own output for seeding. The rails seed file is just a ruby file that gets executed.

I still think it'd be nice to show what's going on during seeding here, I'll take a peek at the code and see if I can cook up a suggestion. For now, I'm just taking your functional seed example and logging to the console in my seed files:

```
// Seed User
module.exports = function(done) {
  var users = [{
    firstName: 'Joe',
    lastName: 'Doe'
  }, {
    firstName: 'Jane',
    lastName: 'Doe'
  }
  }];

  console.log("Seeding users with " + JSON.stringify(users));
  done(null, users);
  console.log("Done seeding users");
};
```

I know sails uses captains-log for logging, perhaps I can hook into that in order to log at the debug level. I'll get back to ya.

**Comment by lykmapipo** [comment]
@kodayashi 

I real like the idea of log. Am open for discussion about what information to log.

**Comment by lykmapipo** [comment]
@kodayashi 

@givanse have helped us with `debug logs`
