### ISSUE TITLE
Seeding not working.

### ISSUE THREAD

**Issue by luisincrespo** [lykmapipo/sails-hook-seed#7]
Hey there.

I just came across your npm package to seed a DB in Sails. Looks pretty simple & great, just what I'm looking for.

 I installed it as:

> npm install --save sails-hook-seed

Created the directories:

> my_sails_app/seeds/development/
> my_sails_app/seeds/production/

I created the file:

> my_sails_app/seeds/development/TeamSeed.js

... with the following code, just to test it:

```
module.exports = [{
    name: 'Test'
}];
```

When I run _sails lift_, the console logs

> debug: loading seeds from:
> debug: /path/to/my_sails_app/seeds/development
> verbose: seed hook loaded successfully.

But when querying the DB, there's nothing in the Team model.

Am I missing something?. Thanks.

**Comment by luisincrespo** [comment]
Sorry, my bad.

I put the file inside the production seeds directory, instead of development which is where I was testing. Completely my bad!!, everything works perfect!.

Thanks. I'm definitely starring your repo.

**Comment by lykmapipo** [comment]
@luisincrespo 

You are welcome
