### ISSUE TITLE
(QUESTION) How to work with associations?

### ISSUE THREAD

**Issue by luisincrespo** [lykmapipo/sails-hook-seed#9]
Is there any way to specify model associations?.

I don't want to hardcode the ids referenced from one model to another, since I want to use the default ids that my mongodb sets.

**Comment by givanse** [comment]
You are in luck, please test PR https://github.com/lykmapipo/sails-hook-seed/pull/10

**Comment by luisincrespo** [comment]
I'll give it a try if I get the time. Thanks.

**Comment by lykmapipo** [comment]
@luisincrespo 

Currently `sails-hook-seed` has not resolution strategy on how to seed relations.

It will be good to have an open discussion on how can we implement this feature with reference from @givanse pull request [#10](https://github.com/lykmapipo/sails-hook-seed/pull/10)

Thanks.
